# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'file-tail'
gem 'slack'
gem 'hash_validator'
gem 'xcodeproj'
gem 'google-api-client'
